### ISSUE TITLE
Bug in gitflow-common script since version 2.2.0

### ISSUE THREAD

**Issue by jrebmann** [CJ-Systems/gitflow-cjs#82] opened 2023-07-29 11:56 UTC
I tried to install the latest version as described in https://github.com/CJ-Systems/gitflow-cjs/wiki/Installing-on-Linux,-Unix,-etc.#manual-installation.

After the installation I got following error:

```shell
$> git flow version
/usr/local/bin/git-flow: 821: /usr/local/bin/gitflow-common: [[: not found
2.2.0 (CJS Edition)
```

The error occurs in this line: https://github.com/CJ-Systems/gitflow-cjs/blob/0ba3329844991d8893fbe58b6b5f87b7b021aeda/gitflow-common#L821

**Comment by ChrisJStone** [comment] 2023-07-29 18:03
Thank you for the report, I'll take a look at this and see what's going on. Having just started a new job I'm not entirely sure when I'll have a change to get a fix pushed out for this.

Update: I tested both develop and stable installs, I was unable to recreate the issue on my development machine which is running Fedora 38 using the default GNOME Terminal app.

One of the comments for the [PR](https://github.com/petervanderdoes/gitflow-avh/pull/165) that introduced the above mentioned change to gitflow-common did mention something about removal of colors preventing this from being merged. However there were no specific details that I could locate as to why this was necessary.

**Comment by jrebmann** [comment] 2023-07-31 19:04
Thanks for your help :)

I am using a standard Ubuntu 22.04 with a default bash.

You can reproduce the error with the following dockerfile:

```Dockerfile
FROM ubuntu:22.04

RUN apt update

RUN apt install -y wget git

RUN wget -q  https://raw.githubusercontent.com/CJ-Systems/gitflow-cjs/develop/contrib/gitflow-installer.sh && \
    bash gitflow-installer.sh install stable; \
    rm gitflow-installer.sh

CMD [ "git", "flow", "version"]
```
If you need help running this Dockerfile, just get in touch.

**Comment by ChrisJStone** [comment] 2023-07-31 21:51
Thank you for providing the docker file for me to use for testing. It allowed me to confirm what I though was the cause. I have removed color support for cherry-picking hotfix commits and the fix has been pushed to the latest release. Please feel free to let me know if you experience any more issues.

**Closed as completed by ChrisJStone** 2023-07-31 21:51 UTC
Labels: Resolution: fixed
